debug: true
server:
  servlet:
    context-path: /
  tomcat:
    accesslog:
      buffered: true
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: tomcat_access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
logging:
  level:
    cn.edu.cqupt.nmid.passloveserver.controller: info
  path: logs
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} ** [%thread] ** %-5level ** %logger{50}** %msg%n"

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/homework?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 1172610139@qq.com
    password: imgqpqvuxsitijje
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  profiles:
    active: dev
config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: token
---
spring:
  profiles: dev

server:
  port: 8080
---
spring:
  profiles: pro
server:
  port: 8081